# Copyright (C) 2015 The AOSPERIA Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/tulip/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/tulip/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
    vendor/sony/tulip/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    vendor/sony/tulip/proprietary/bin/imscmservice:system/bin/imscmservice \
    vendor/sony/tulip/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    vendor/sony/tulip/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/sony/tulip/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
    vendor/sony/tulip/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/sony/tulip/proprietary/lib/hw/camera.msm8916.so:system/lib/hw/camera.msm8916.so \
    vendor/sony/tulip/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/sony/tulip/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
    vendor/sony/tulip/proprietary/vendor/bin/sound_trigger_test:system/vendor/bin/sound_trigger_test \
    vendor/sony/tulip/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/sony/tulip/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/sony/tulip/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/sony/tulip/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/sony/tulip/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/sony/tulip/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_audio.so:system/vendor/lib/mmi_audio.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_battery.so:system/vendor/lib/mmi_battery.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_bt.so:system/vendor/lib/mmi_bt.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_flashlight.so:system/vendor/lib/mmi_flashlight.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_fm.so:system/vendor/lib/mmi_fm.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_gps_garden.so:system/vendor/lib/mmi_gps_garden.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_gsensor.so:system/vendor/lib/mmi_gsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_gyroscope.so:system/vendor/lib/mmi_gyroscope.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_key.so:system/vendor/lib/mmi_key.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_keypadbacklight.so:system/vendor/lib/mmi_keypadbacklight.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_lcd.so:system/vendor/lib/mmi_lcd.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_led.so:system/vendor/lib/mmi_led.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_lsensor.so:system/vendor/lib/mmi_lsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_msensor.so:system/vendor/lib/mmi_msensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_nfc.so:system/vendor/lib/mmi_nfc.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_psensor.so:system/vendor/lib/mmi_psensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_sdcard.so:system/vendor/lib/mmi_sdcard.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_sim.so:system/vendor/lib/mmi_sim.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_sysinfo.so:system/vendor/lib/mmi_sysinfo.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_touch.so:system/vendor/lib/mmi_touch.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_touchpanel.so:system/vendor/lib/mmi_touchpanel.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_vibrator.so:system/vendor/lib/mmi_vibrator.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_volume.so:system/vendor/lib/mmi_volume.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_wifi.so:system/vendor/lib/mmi_wifi.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_audio.so:system/vendor/lib64/mmi_audio.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_battery.so:system/vendor/lib64/mmi_battery.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_bt.so:system/vendor/lib64/mmi_bt.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_flashlight.so:system/vendor/lib64/mmi_flashlight.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_fm.so:system/vendor/lib64/mmi_fm.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_gps_garden.so:system/vendor/lib64/mmi_gps_garden.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_gsensor.so:system/vendor/lib64/mmi_gsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_gyroscope.so:system/vendor/lib64/mmi_gyroscope.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_key.so:system/vendor/lib64/mmi_key.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_keypadbacklight.so:system/vendor/lib64/mmi_keypadbacklight.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_lcd.so:system/vendor/lib64/mmi_lcd.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_led.so:system/vendor/lib64/mmi_led.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_lsensor.so:system/vendor/lib64/mmi_lsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_msensor.so:system/vendor/lib64/mmi_msensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_nfc.so:system/vendor/lib64/mmi_nfc.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_psensor.so:system/vendor/lib64/mmi_psensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_sdcard.so:system/vendor/lib64/mmi_sdcard.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_sim.so:system/vendor/lib64/mmi_sim.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_sysinfo.so:system/vendor/lib64/mmi_sysinfo.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_touch.so:system/vendor/lib64/mmi_touch.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_touchpanel.so:system/vendor/lib64/mmi_touchpanel.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_vibrator.so:system/vendor/lib64/mmi_vibrator.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_volume.so:system/vendor/lib64/mmi_volume.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_wifi.so:system/vendor/lib64/mmi_wifi.so 
